### ISSUE TITLE
License information is missing

### ISSUE THREAD

**Issue by marians** [apiaxle/apiaxle#116]
The repository should have a `LICENSE.txt` file so it's easy to figure out under what license the source is published.

**Comment by longrunningprocess** [comment]
Thanks @marians , would simply renaming https://github.com/apiaxle/apiaxle/blob/develop/GPL-3.0.txt to `LICENSE.txt` do it?

**Comment by marians** [comment]
YES. (I missed that!)

**Comment by longrunningprocess** [comment]
ok, @marians , the PR is in.  @fillup should be able to get to this sometime this week.
