### ISSUE TITLE
An option to find keyring(s) a key belongs to

### ISSUE THREAD

**Issue by vlcinsky** [apiaxle/apiaxle#49]
Sometime I need to track, who is consuming my resources. Knowing api_key from logs, I want to find which keyring it belongs to.

In current version of ApiAxle API I did not find the way to list keyring(s), a key belongs to. The only method is from the other side - loop through all keyrings and list their apikeys, checking, where is they key I care about mentioned.

As workaround I could find that information in Redis:
```bash
$ redis-cli
127.0.0.1:6379> hgetall "gk:development:key:javl-keyrings"
1) "jan.vlcinsky"
2) "1"
127.0.0.1:6379> 
```

It would be great to see that option via API too.

(PS: I am a Python guy, so it would take me a bit longer to add such modification in your code, but I may try later on, if there is a need and time)

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
