### ISSUE TITLE
Feature Request - Add the ability to register custom request and response filters

### ISSUE THREAD

**Issue by nrdsrfr** [apiaxle/apiaxle#53]
Similar to the pattern used in [Netflix's Zuul](https://github.com/Netflix/zuul), providing a framework to register filters would allow API Axle developers the ability to create a set of actions that would run on the request where applicable before it's passed to the origin, and likewise more actions to be applied to the response on the way out. 

These actions might be to do something simple like adding headers or fields to the request/response body (very easily done with JSON in node/coffeescript) or something more complex like creating callouts to other services to do some sort of authorisation to add a JWT header or grab data from another API necessary for the request or for a mashup response.

See [IZuulFilter](zuul-core/src/main/java/com/netflix/zuul/IZuulFilter.java) for the basic interface which is simply `boolean shouldFilter()` to decide whether to run the filter and `run()` to run it.

Also see the abstract [ZuulFilter](zuul-core/src/main/java/com/netflix/zuul/ZuulFilter.java) to see the base filter which includes some more functions, most importantly ordering where necessary (otherwise filters can run concurrently)

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
