### ISSUE TITLE
Allow custom meta error response

### ISSUE THREAD

**Issue by whamilton42** [apiaxle/apiaxle#56]
The way in which apiaxle returns its own errors is different to our API. For example, when an API key is not valid:

    {"meta":{"version":1,"status_code":403},"results":{"error":{"type":"KeyError","message":"'xxx' is not a valid key."}}}

This error message includes information about apiaxle itself. We don't want to show this to users. It would be very useful if it was possible to configure apiaxle to return errors in a particular format.

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
