### ISSUE TITLE
Feature request - Add option to expire regular API keys

### ISSUE THREAD

**Issue by joecise** [apiaxle/apiaxle#63]
I have an outside system that is provisioning API keys on ApiAxle, and would like for ApiAxle to expire these keys after a set period of time, similar to the temporary keys that are created in "keyless" mode, but the TTL would be set on a per key basis at the time of key creation. One hitch is these keys are attached to keyrings, so this relationship would also need expiring.

Thanks.

**Comment by michaeljclark** [comment]
I'm also investigating adding support for key TTLs, however instead of expiring the keys in Redis I am thinking about adding a TTL attribute to the key records in Redis. This means we can keep a record of a keys with expired TTLs and there would be no broken linkages (as there would be using Redis TTLs). The key TTL can be then be modified through the API to extend it or remove the TTL (set to -1).

CoffeeScript is not my forte so I would appreciate some help with getting this logic into api_limits.coffee. Something like this:

```
   now = Date.now()
   expired = true if key.createdAt + key.ttl > now
```

This model change is where I am currently at with the TTL feature:

```
diff --git a/base/app/model/redis/key_factory.coffee b/base/app/model/redis/key_factory.coffee
index 5f32578..0bbd4be 100644
--- a/base/app/model/redis/key_factory.coffee
+++ b/base/app/model/redis/key_factory.coffee
@@ -96,6 +96,10 @@ class exports.KeyFactory extends Redis
         type: "integer"
         default: 2
         docs: "Number of queries that can be called per second. Set to `-1` for no limit."
+      ttl:
+        type: "integer"
+        default: -1
+        docs: "Number of seconds until the key expires. Set to `-1` for no expiry."
       forApis:
         optional: true
         type: "array"
```

**Comment by michaeljclark** [comment]
Alternatively we were thinking about adding a 'class' attribute to keys and getting Apiaxle to add some headers e.g. 'X-ApiaxleProxy-Key-Class' and 'X-ApiaxleProxy-Key-Created-At'. This would allow the API behind Apiaxle to police differing TTLs for differing classes of keys.

However TTL seems like a reasonable addition to QPS and QPD enforcement. :+1:

**Comment by michaeljclark** [comment]
This appears to work:

```
diff --git a/base/app/model/redis/key_factory.coffee b/base/app/model/redis/key_factory.coffee
index 5f32578..0bbd4be 100644
--- a/base/app/model/redis/key_factory.coffee
+++ b/base/app/model/redis/key_factory.coffee
@@ -96,6 +96,10 @@ class exports.KeyFactory extends Redis
         type: "integer"
         default: 2
         docs: "Number of queries that can be called per second. Set to `-1` for no limit."
+      ttl:
+        type: "integer"
+        default: -1
+        docs: "Number of seconds until the key expires. Set to `-1` for no expiry."
       forApis:
         optional: true
         type: "array"
diff --git a/proxy/apiaxle-proxy.coffee b/proxy/apiaxle-proxy.coffee
index be86404..2686190 100755
--- a/proxy/apiaxle-proxy.coffee
+++ b/proxy/apiaxle-proxy.coffee
@@ -301,6 +301,12 @@ class exports.ApiaxleProxy extends AxleApp
       req.key.data.qpd
     ]
 
+    # check for key expiry
+    now = Date.now()
+    expiresAt = req.key.data.createdAt + req.key.data.ttl * 1000
+    expired = req.key.data.ttl != -1 and expiresAt < now
+    return next new KeyError "API Key has expired" if expired 
+
     @model( "apilimits" ).apiHit args..., ( err, [ newQpd, newQps ] ) ->
       return next err if err
 
```

**Comment by onetom** [comment]
@michaeljclark thanks for the patch.unfortunately we can't just incorporate it without corresponding tests.

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
