### ISSUE TITLE
Values of X-ApiaxleProxy-Qps-Left and X-ApiaxleProxy-Qpd-Left are reversed

### ISSUE THREAD

**Issue by joecise** [apiaxle/apiaxle#64]
My coffee script understand basically only comes from reading ApiAxle source code, but I think the variables here are back to front:

https://github.com/apiaxle/apiaxle/blob/c6e4c1c035266109dac2b05c817fa7fd22350d76/proxy/apiaxle-proxy.coffee#L302

**Comment by sleepylemur** [comment]
the code was written in a confusing way but was actually correct.

**Comment by fillup** [comment]
Thanks for clearing up @sleepylemur
