### ISSUE TITLE
Using apiaxle with redis instance that requires auth

### ISSUE THREAD

**Issue by angelo0000** [apiaxle/apiaxle#67]
I can not figure out how to configure my json file so that when apiaxle connects to redis it uses our auth key.  I have looked on the site and see the config example which only includes host and port.  Does ApiAxle support connecting to a redis instance that requires auth?

**Comment by coderofsalvation** [comment]
I'm facing the same problem and using angelo's fork now.
Redis auth is very usual on cloud services, so I highly recommend pulling angelo's commit.

**Comment by angelo0000** [comment]
It was pulled in here: https://github.com/apiaxle/apiaxle/commit/1697bd73f6c274dc721d03373b369829e1f33ded

**Comment by coderofsalvation** [comment]
Thank you for your answer.
Strange I did an npm install apiaxle-proxy and it wasnt included in there.
Should I use their development branch of apiaxle instead?

**Comment by fillup** [comment]
We recently merged develop into master and released version 1.14.0 so I believe this is included there. If not please reopen this issue.
