### ISSUE TITLE
Suppressing version tag

### ISSUE THREAD

**Issue by lucasgonze** [apiaxle/apiaxle#70]
For the design of our API we would sometimes like to have no version tag in a URI. 

(As a policy choice, the plan is to add a version tag if we do a breaking change, but otherwise omit the tag, in order to keep the URI short and pretty. So /foo would be succeeded by /v2/foo).

There appears to be no way to do this with ApiAxle as it is currently implemented. Is that right?

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
