### ISSUE TITLE
Can't install apiaxle modules using node 0.12.x

### ISSUE THREAD

**Issue by kovalchuck** [apiaxle/apiaxle#71]
Issue with installing apiaxle modules: can't install apiaxle because libxmljs@0.7.1 has compilation problems. There is no problems with libxmljs@0.14.0
https://github.com/papandreou/node-cldr/issues/16
Issue on libxmljs's github: https://github.com/polotek/libxmljs/issues/238

**Comment by ambahk** [comment]
Here's a more recent related issue: https://github.com/polotek/libxmljs/issues/303

**Comment by ambahk** [comment]
One of the dependencies also need to be updated https://github.com/philjackson/js2xml/issues/7

**Comment by philjackson** [comment]
I've pushed the change to js2xml.

**Comment by onlyforart** [comment]
This has not been resolved in the current build: api/package.json still contains
    "libxmljs": "~0.7.1",
