### ISSUE TITLE
have a response template for apiaxle response

### ISSUE THREAD

**Issue by aberthier** [apiaxle/apiaxle#73]
Hello,

It would be very usefull to have a response template to keep consistency between API responses and apiAxle responses.
e.g. the common apiAxle response: 
```javascript
{
  "meta": {
    "version": 1,
    "status_code": 403
  },
  "results": {
    "error": {
      "type": "KeyError",
      "message": "No api_key specified."
    }
  }
}
```

Our current response template:
```javascript
{
  "status": "OK",
  "response": [],
  "error": null
}
```

**Comment by aberthier** [comment]
Sorry duplicate of 56

**Comment by wcjr** [comment]
duplicate #56

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
