### ISSUE TITLE
Adding capture path

### ISSUE THREAD

**Issue by subburajvlb** [apiaxle/apiaxle#79]
I have configured an api name "places" with endpoint "localhost:2100". My API has many routes, now i want to add capture path to the configured "places" api in ApiAxle so tthat i can get the statistics for that particular API.

I am using the following PUT API From the documentation:

curl -H 'content-type: application/json' \
	-X PUT \
	'http://localhost:3000/v1/api/places/addcapturepath/localhost:2100/xx/yy/zz'
But i am getting the error:

{"meta":{"version":1,"status_code":404},"results":{"error":{"type":"NotFoundError","message":"'/v1/api/places/addcapturepath/localhost:2100/xx/yy/zz' not found."}}}

In what way i have to specify the capture path.

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
