### ISSUE TITLE
Proxy veyr slow during our load tests

### ISSUE THREAD

**Issue by ejether** [apiaxle/apiaxle#80]
I'm hoping you can help me optimize the configuration of the proxy for our service load test.
We are using [](http://gatling.io/docs/2.0.1/quickstart.html) to stress test through apiaxle with 4800 connections over 5 minutes and I think we have reached the limit apiaxle, at least as we have it configured.

Our setup:
APIAxle is running in a docker container behind and nginx reverse proxy. 
We have a cluster of 6 machines with round robin load balancing for each service via haproxy.
The complete path for an incoming request is:
nginx -> haproxy -> api axle (6 instances 8 forks on 8 core machines) -> our service  

When I remove apiaxle from the chain, we have no problems. When apiaxle is included in that chain we quickly run into 504s from apiaxle and 502 from nginx.  I'm inclined to believe that the 504 timeouts are not due to slowness in our service, since without apiaxle in the chain, our response times are still ~60ms during the load test

I was hoping you might have some ideas for things I can try for optimization.
Thanks

**Comment by fillup** [comment]
Cleaning up old issues. If this is still an issue for you please reopen.
