### ISSUE TITLE
Tests break because of hard-coded date

### ISSUE THREAD

**Issue by sleepylemur** [apiaxle/apiaxle#83]
If this date:
https://github.com/apiaxle/apiaxle/blob/develop/api/test/app/controller/v1/stats_controller_test.coffee#L49
is in the past, then redis expires stats immediately during the test, causing the tests to fail.

Expiring being done here:
https://github.com/apiaxle/apiaxle/blob/develop/base/app/model/redis/stats.coffee#L67

**Comment by wcjr** [comment]
looks like this one may be closeable as a result of your work in #85, correct @sleepylemur ?

**Comment by sleepylemur** [comment]
@wcjr yes the fix has been merged already. Closing.
