### ISSUE TITLE
Keyless x-forwarded-for not handled well

### ISSUE THREAD

**Issue by sleepylemur** [apiaxle/apiaxle#96]
When a keyless key is created, if x-forwarded-for is set, [the current method](https://github.com/apiaxle/apiaxle/blob/develop/proxy/apiaxle-proxy.coffee#L112-L121) is to use the entire header in the name of the key.

At Mapzen we use Fastly as an edge cache in front of some of our APIs, and requests from a single ip address will generate upwards of 40 keys.

For example a user at 111-111-111-111 would have the following keys generated:

ip-vector-tiles-111-111-111-111,%2023.235.43.20
ip-vector-tiles-111-111-111-111,%2023.235.43.21
...
ip-vector-tiles-111-111-111-111,%2023.235.43.51
etc.

where 23.235.43.20 is one of the Fastly ips.

It seems that only using the first comma separated ip would be expected behavior, though it is easily faked. Thoughts? @wcjr @fillup @nvkelso

**Comment by wcjr** [comment]
not sure about this one...I wonder if @philjackson could enlighten us on his original intent?

**Comment by sleepylemur** [comment]
It was listed as a TODO

comment from the code before I amended it:
https://github.com/apiaxle/apiaxle/blob/7756ee675b2160c3550cca38a4c0b3deac4af746/proxy/apiaxle-proxy.coffee#L112-L119

**Comment by wcjr** [comment]
is concatenating them (or some form of them) a reasonable option (not sure if a size limit exists)?

**Comment by sleepylemur** [comment]
concatenating is essentially what's being done now, but it results in a single user being issued upwards of 40 keys in our setup, which makes rate limiting and usage tracking rather difficult. Basically every time the user makes a request, they randomly use one of their 40 keys, depending on which fastly ip they ended up routing through.

**Comment by wcjr** [comment]
yeah, I don't think I understand all of it well enough to lend any _helpful_ advice, sorry man.

**Comment by philjackson** [comment]
I'm not sure on the specs for x-forwarded-for, but does it say anything about the order of the IP addresses? It might be that taking the first is fine?

**Comment by wcjr** [comment]
This may be a relevant section from the [RFC 7239](https://tools.ietf.org/html/rfc7239#section-5.2):

> In a chain of proxy servers where this is fully utilized, the first
   "for" parameter will disclose the client where the request was first
   made, followed by any subsequent proxy identifiers.  The last proxy
   in the chain is not part of the list of "for" parameters.  The last
   proxy's IP address, and optionally a port number, are, however,
   readily available as the remote IP address at the transport layer.
   It can, however, be more relevant to read information about the last
   proxy from preceding "Forwarded" header field's "by" parameter, if
   present.
